namespace lobby {
    export var res = {
        girlJson: "res/common/Animation/douqimeinv.json",
        girlAtlas: "res/common/Animation/douqimeinv.atlas",
        girlPng: "res/common/Animation/douqimeinv.png",
        lgnBlnJson: "res/common/Animation/Login/huxi.json",
        lgnBlnAtlas: "res/common/Animation/Login/huxi.atlas",
        lgnBlnPng: "res/common/Animation/Login/huxi.png",
        seagull_plist: "res/common/Animation/seagull.plist",
        //签到按钮动画
        singInAni_json: "res/common/Animation/qiaodao.json",
        singInAni_atlas: "res/common/Animation/qiaodao.atlas",
        singInAni_png: "res/common/Animation/qiaodao.png",
        sweep_plist: "res/common/Animation/sweep.plist",
        tmodelbg_img: "res/common/bgs/common.tmodelbg.jpg",
        wave_plist: "res/common/Animation/wave.plist",
        MapPanel_img: "res/lobby/AreaSelectionPanel/MapPanel.png",

        AgreementPanel_json: "res/lobby/AgreementPanel/AgreementPanel.json",
        DisclaimerPanel_json: "res/lobby/DisclaimerPanel/DisclaimerPanel.json",
        ForeignIPPanel_json: "res/lobby/ForeignIPPanel/ForeignIPPanel.json",
        Lobby_json: "res/lobby/LobbyScene.json",
        Login_json: "res/lobby/Login/LoginScene.json",
        NumberInputPanel_json: "res/lobby/NumberInputPanel/NumberInputPanel.json",
        UserInfoPanel_json: "res/lobby/UserInfoPanel/UserInfoPanel.json",
        GameOptionsBtnGroup_json: "res/lobby/GameOptionsBtnGroup/GameOptionsBtnGroup.json",
        UserInfoBlock_json: "res/lobby/UserInfoBlock/UserInfoBlock.json",
        TopMenuBlock_json: "res/lobby/TopMenuBlock/TopMenuBlock.json",
        BottomMeunBlock_json: "res/lobby/BottomMeunBlock/BottomMeunBlock.json",
        // GDGameBlock_json: "res/lobby/GDGameBlock/GDGameBlock.json",
        // GDGameRoomPanel_json: "res/lobby/GDGameBlock/GDGameRoomPanel.json",
        CreateRoomPanel_json: "res/lobby/CreateRoomPanel/CreateRoomPanel.json",
        // RankListPanel_json: "res/lobby/RankListPanel/RankListPanel.json",
        JoinRoomPanel_json: "res/lobby/JoinRoomPanel/JoinRoomPanel.json",
        RecruitingPanel_json: "res/lobby/RecruitingPanel/RecruitingPanel.json",
        AreaSelectionPanel_json: "res/lobby/AreaSelectionPanel/AreaSelectionPanel.json",
        AreaSelectionName_plist: "res/lobby/AreaSelectionPanel/CityName.plist",
        AreaSelectionName_png: "res/lobby/AreaSelectionPanel/CityName.png",
        MallPanel_json: "res/lobby/MallPanel/MallPanel.json",
        // ExchangePanel_json: "res/lobby/ExchangePanel/ExchangePanel.json",
        mallBindPanel_json: "res/lobby/MallPanel/MallBindPanel.json",
        ExchangeSusPanel_json: "res/lobby/MallPanel/Mall_exchangeSusPanel.json",
        ChannelPanel_json: "res/lobby/MallPanel/ChannelPanel.json",
        NoticePanel_json: "res/lobby/NoticePanel/NoticePanel.json",
        ContractPanel_json: "res/lobby/NoticePanel/ContractPanel.json",
        CustomRegOutPanel_json: "res/lobby/NoticePanel/CustomRegOutPanel.json",
        // RuleIntroducePanel_json: "res/lobby/RuleIntroducePanel/RuleIntroducePanel.json",
        PolicyPanel_json: "res/lobby/PolicyPanel/PolicyPanel.json",
        CustomerServicePanel_json: "res/lobby/CustomerServicePanel/CustomerServicePanel.json",
        RealNamePanel_json: "res/lobby/RealNamePanel/RealNamePanel.json",
        IllegalReportingPanel_json: "res/lobby/IllegalReportingPanel/IllegalReportingPanel.json",

        SuggestionPanel_json: "res/lobby/SuggestionPanel/SuggestionPanel.json",
        SuggestionFeedbackPanel_json: "res/lobby/SuggestionPanel/SuggestionFeedbackPanel.json",

        ShareModelPanel_json: "res/lobby/ShareModelPanel/ShareModelPanel.json",
        // InsureBoxPanel_json: "res/lobby/InsureBoxPanel/InsureBoxPanel.json",
        BindWechatPanel_json: "res/lobby/BindWechatPanel/BindWechatPanel.json",
        // LoginCsPanel_Json: "res/lobby/Login/LoginCsPanel/LoginCsLayer.json",
        BindPhonePanel_json: "res/lobby/UserInfoPanel/BindPhonePanel.json",                         //绑定解绑手机界面
        PhoneLoginPanel_json: "res/lobby/PhoneLoginPanel/PhoneLoginPanel.json",
        // PhoneRegsterPlane_json: "res/lobby/PhoneLoginPanel/PhoneRegsterPlane.json",
        // PhoneFindPlane_json: "res/lobby/PhoneLoginPanel/PhoneFindPlane.json",
        PmdPanel_json: "res/lobby/PmdPanel/PmdPanel.json",
        PmdSendLabaPanel_json: "res/lobby/PmdPanel/PmdSendLabaPanel.json",
        // DibaoPanel_json: "res/lobby/DibaoPanel/DibaoPanel.json",
        // SignPanel_json: "res/lobby/SignPanel/SignPanel.json",
        // GainRewardPanel_json: "res/lobby/GainRewardPanel/GainRewardPanel.json",

        GameCenterPanel_json: "res/lobby/GameCenterPanel/GameCenterPanel.json",
        RecordPanel_json: "res/lobby/RecordPanel/RecordPanel.json",
        JoinRecordPanel_json: "res/lobby/RecordPanel/JoinRecordPanel.json",
        MaintainNotice_Json: "res/lobby/NoticePanel/MaintainLayer.json",
        ShareImagePanel_json: "res/lobby/ShareResource/ShareImagePanel.json",
        ShareRecord_Json: "res/lobby/ShareModelPanel/ShareRecoredPanel.json",
        // Action_mask_plist: "res/lobby/SignPanel/action_mask.plist",
        // PackageIcon_plist:"res/lobby/GameIcons/GameIcon.plist"
        huxiAnimation_json: "res/common/Animation/huxi.json",
        huxiAnimation_atlas: "res/common/Animation/huxi.atlas",
        huxiAnimation_png: "res/common/Animation/huxi.png",
        LobbyBindIDPanel_json: "res/lobby/lobbyBindPanel/LobbyBindIDPanel.json",     //大厅绑定按钮
        LobbyBindPanel_json: "res/lobby/lobbyBindPanel/LobbyBindPanel.json",
        LobbySignInPanel_json: "res/lobby/SignInPanel/signPanel.json",
        LobbyDisposeAllowancesPanel_json: "res/lobby/DisposeAllowancesPanel/DisposeAllowancesPanel.json",
        //金币掉落
        reward_json: "res/common/Animation/Reward.json",
        reward_atlas: "res/common/Animation/Reward.atlas",
        reward_png: "res/common/Animation/Reward.png",
        //金币场进入动画
        goldEnterAni_json: "res/common/Animation/jinbc.json",
        goldEnterAni_atlas: "res/common/Animation/jinbc.atlas",
        goldEnterAni_png: "res/common/Animation/jinbc.png",
        goldEnterAniDdz_json: "res/common/Animation/ddz.json",
        goldEnterAniDdz_atlas: "res/common/Animation/ddz.atlas",
        goldEnterAniDdz_png: "res/common/Animation/ddz.png",
        //金币兑换成功动画
        exChangeGoldAni_json: "res/common/Animation/dhcg.json",
        exChangeGoldAni_atlas: "res/common/Animation/dhcg.atlas",
        exChangeGoldAni_png: "res/common/Animation/dhcg.png",
        //传奇动画
        legendAni_json: "res/common/Animation/dragon_d.json",
        legendAni_atlas: "res/common/Animation/dragon_d.atlas",
        legendAni_png: "res/common/Animation/dragon_d.png",

        authSettingPanel_json: "res/lobby/TopMenuBlock/lobby_authorityPanel.json",
        //fnt
        lobby_share_bignum_fnt: "res/lobby/ShareResource/fnt/lobby.share.bignum.fnt",
        lobby_share_bignumwin_fnt: "res/lobby/ShareResource/fnt/lobby.share.bignumwin.fnt"

    };

    export var GameIcons = {
        bmhm: "res/lobby/GameIcons/bmhm.png",
        cbdg: "res/lobby/GameIcons/cbdg.png",
        cbmj: "res/lobby/GameIcons/cbmj.png",
        cemj: "res/lobby/GameIcons/cemj.png",
        cydg: "res/lobby/GameIcons/cydg.png",
        cyhqj: "res/lobby/GameIcons/cyhqj.png",
        cymj: "res/lobby/GameIcons/cymj.png",
        czmj: "res/lobby/GameIcons/czmj.png",
        czpdk: "res/lobby/GameIcons/czpdk.png",
        dbd: "res/lobby/GameIcons/dbd.png",
        ddz: "res/lobby/GameIcons/ddz.png",
        dy510k: "res/lobby/GameIcons/dy510k.png",
        dydg: "res/lobby/GameIcons/dydg.png",
        dymj: "res/lobby/GameIcons/dymj.png",
        dyrar: "res/lobby/GameIcons/dyrar.png",
        dyzp: "res/lobby/GameIcons/dyzp.png",
        esgdy: "res/lobby/GameIcons/esgdy.png",
        esmj: "res/lobby/GameIcons/esmj.png",
        espdk: "res/lobby/GameIcons/espdk.png",
        essh: "res/lobby/GameIcons/essh.png",
        ez510k: "res/lobby/GameIcons/ez510k.png",
        ezhh: "res/lobby/GameIcons/ezhh.png",
        ezmj: "res/lobby/GameIcons/ezmj.png",
        fymj: "res/lobby/GameIcons/fymj.png",
        gdtdh: "res/lobby/GameIcons/gdtdh.png",
        gdy: "res/lobby/GameIcons/gdy.png",
        hchz: "res/lobby/GameIcons/hchz.png",
        hcmj: "res/lobby/GameIcons/hcmj.png",
        hcsj: "res/lobby/GameIcons/hcsj.png",
        hfbh: "res/lobby/GameIcons/hfbh.png",
        hfmj: "res/lobby/GameIcons/hfmj.png",
        hgmj: "res/lobby/GameIcons/hgmj.png",
        hh510k: "res/lobby/GameIcons/hh510k.png",
        hhhj: "res/lobby/GameIcons/hhhj.png",
        hhmj: "res/lobby/GameIcons/hhmj.png",
        hmmj: "res/lobby/GameIcons/hmmj.png",
        hs510k: "res/lobby/GameIcons/hs510k.png",
        hsmj: "res/lobby/GameIcons/hsmj.png",
        hzhh: "res/lobby/GameIcons/hzhh.png",
        hzlzg: "res/lobby/GameIcons/hzlzg.png",
        jhpdk: "res/lobby/GameIcons/jhpdk.png",
        jiaozuomj: "res/lobby/GameIcons/jiaozuomj.png",
        jlkj: "res/lobby/GameIcons/jlkj.png",
        jlmj: "res/lobby/GameIcons/jlmj.png",
        jmmj: "res/lobby/GameIcons/jmmj.png",
        jsch: "res/lobby/GameIcons/jsch.png",
        jsmj: "res/lobby/GameIcons/jsmj.png",
        jydg: "res/lobby/GameIcons/jydg.png",
        jymj: "res/lobby/GameIcons/jymj.png",
        jzcxz: "res/lobby/GameIcons/jzcxz.png",
        jzhp: "res/lobby/GameIcons/jzhp.png",
        jzkwx: "res/lobby/GameIcons/jzkwx.png",
        jzmj: "res/lobby/GameIcons/jzmj.png",
        jzpdk: "res/lobby/GameIcons/jzpdk.png",
        lamj: "res/lobby/GameIcons/lamj.png",
        lcddz: "res/lobby/GameIcons/lcddz.png",
        lcsdr: "res/lobby/GameIcons/lcsdr.png",
        ltmj: "res/lobby/GameIcons/ltmj.png",
        mcmj: "res/lobby/GameIcons/mcmj.png",
        pdk: "res/lobby/GameIcons/pdk.png",
        qcdg: "res/lobby/GameIcons/qcdg.png",
        qcmj: "res/lobby/GameIcons/qcmj.png",
        qj510k: "res/lobby/GameIcons/qj510k.png",
        qjmj: "res/lobby/GameIcons/qjmj.png",
        quanjiaomj: "res/lobby/GameIcons/quanjiaomj.png",
        ss510k: "res/lobby/GameIcons/ss510k.png",
        ssah: "res/lobby/GameIcons/ssah.png",
        sykwx: "res/lobby/GameIcons/sykwx.png",
        szkwx: "res/lobby/GameIcons/szkwx.png",
        tcbg: "res/lobby/GameIcons/tcbg.png",
        tcdg: "res/lobby/GameIcons/tcdg.png",
        tcgz: "res/lobby/GameIcons/tcgz.png",
        tcmj: "res/lobby/GameIcons/tcmj.png",
        tfmj: "res/lobby/GameIcons/tfmj.png",
        tm510k: "res/lobby/GameIcons/tm510k.png",
        tmmj: "res/lobby/GameIcons/tmmj.png",
        tsdg: "res/lobby/GameIcons/tsdg.png",
        tsmj: "res/lobby/GameIcons/tsmj.png",
        wdtdh: "res/lobby/GameIcons/wdtdh.png",
        wx510k: "res/lobby/GameIcons/wx510k.png",
        wxgb: "res/lobby/GameIcons/wxgb.png",
        wxmj: "res/lobby/GameIcons/wxmj.png",
        xgkwx: "res/lobby/GameIcons/xgkwx.png",
        xiaogankwx: "res/lobby/GameIcons/xiaogankwx.png",
        xlch: "res/lobby/GameIcons/xlch.png",
        xndg: "res/lobby/GameIcons/xndg.png",
        xnhh: "res/lobby/GameIcons/xnhh.png",
        xnhzlzg: "res/lobby/GameIcons/xnhzlzg.png",
        xsdq: "res/lobby/GameIcons/xsdq.png",
        xsmj: "res/lobby/GameIcons/xsmj.png",
        xtmj: "res/lobby/GameIcons/xtmj.png",
        xtpdk: "res/lobby/GameIcons/xtpdk.png",
        xtqf: "res/lobby/GameIcons/xtqf.png",
        xtqfbd: "res/lobby/GameIcons/xtqfbd.png",
        xxmj: "res/lobby/GameIcons/xxmj.png",
        xykwx: "res/lobby/GameIcons/xykwx.png",
        ychh: "res/lobby/GameIcons/ychh.png",
        yckwx: "res/lobby/GameIcons/yckwx.png",
        ycsdr: "res/lobby/GameIcons/ycsdr.png",
        ycxlch: "res/lobby/GameIcons/ycxlch.png",
        yichangsdr: "res/lobby/GameIcons/yichangsdr.png",
        yxdg: "res/lobby/GameIcons/yxdg.png",
        yxmj: "res/lobby/GameIcons/yxmj.png",
        yxzp: "res/lobby/GameIcons/yxzp.png",
        zjkmj: "res/lobby/GameIcons/zjkmj.png",
        zjkpdk: "res/lobby/GameIcons/zjkpdk.png",
        zjkphdl: "res/lobby/GameIcons/zjkphdl.png",
        zxtm: "res/lobby/GameIcons/zxtm.png"
    }

    export var AreaGameTitle = {
        130700: "res/lobby/GameIcons/AreaGameTitle/130700.png",
        341100: "res/lobby/GameIcons/AreaGameTitle/341100.png",
        341122: "res/lobby/GameIcons/AreaGameTitle/341122.png",
        341124: "res/lobby/GameIcons/AreaGameTitle/341124.png",
        341200: "res/lobby/GameIcons/AreaGameTitle/341200.png",
        410700: "res/lobby/GameIcons/AreaGameTitle/410700.png",
        410800: "res/lobby/GameIcons/AreaGameTitle/410800.png",
        420100: "res/lobby/GameIcons/AreaGameTitle/420100.png",
        420200: "res/lobby/GameIcons/AreaGameTitle/420200.png",
        420222: "res/lobby/GameIcons/AreaGameTitle/420222.png",
        420281: "res/lobby/GameIcons/AreaGameTitle/420281.png",
        420300: "res/lobby/GameIcons/AreaGameTitle/420300.png",
        420500: "res/lobby/GameIcons/AreaGameTitle/420500.png",
        420600: "res/lobby/GameIcons/AreaGameTitle/420600.png",
        420700: "res/lobby/GameIcons/AreaGameTitle/420700.png",
        420800: "res/lobby/GameIcons/AreaGameTitle/420800.png",
        420821: "res/lobby/GameIcons/AreaGameTitle/420821.png",//荆门市京山县，原来是420882
        420881: "res/lobby/GameIcons/AreaGameTitle/420881.png",
        420900: "res/lobby/GameIcons/AreaGameTitle/420900.png",
        420981: "res/lobby/GameIcons/AreaGameTitle/420981.png",
        420984: "res/lobby/GameIcons/AreaGameTitle/420984.png",
        421000: "res/lobby/GameIcons/AreaGameTitle/421000.png",
        421023: "res/lobby/GameIcons/AreaGameTitle/421023.png",
        421081: "res/lobby/GameIcons/AreaGameTitle/421081.png",
        421083: "res/lobby/GameIcons/AreaGameTitle/421083.png",
        421100: "res/lobby/GameIcons/AreaGameTitle/421100.png",
        421102: "res/lobby/GameIcons/AreaGameTitle/421102.png",//黄冈市黄冈区
        421121: "res/lobby/GameIcons/AreaGameTitle/421121.png",
        421123: "res/lobby/GameIcons/AreaGameTitle/421123.png",
        421125: "res/lobby/GameIcons/AreaGameTitle/421125.png",
        421126: "res/lobby/GameIcons/AreaGameTitle/421126.png",
        421127: "res/lobby/GameIcons/AreaGameTitle/421127.png",
        421182: "res/lobby/GameIcons/AreaGameTitle/421182.png",
        421200: "res/lobby/GameIcons/AreaGameTitle/421200.png",
        421202: "res/lobby/GameIcons/AreaGameTitle/421200.png",//咸宁市咸安区
        421221: "res/lobby/GameIcons/AreaGameTitle/421221.png",
        421222: "res/lobby/GameIcons/AreaGameTitle/421222.png",
        421223: "res/lobby/GameIcons/AreaGameTitle/421223.png",
        421224: "res/lobby/GameIcons/AreaGameTitle/421224.png",
        421281: "res/lobby/GameIcons/AreaGameTitle/421281.png",
        421300: "res/lobby/GameIcons/AreaGameTitle/421300.png",
        422801: "res/lobby/GameIcons/AreaGameTitle/422801.png",//恩施州恩施市
        422802: "res/lobby/GameIcons/AreaGameTitle/422802.png",
        422828: "res/lobby/GameIcons/AreaGameTitle/422828.png",
        429004: "res/lobby/GameIcons/AreaGameTitle/429004.png",
        429005: "res/lobby/GameIcons/AreaGameTitle/429005.png",
        429006: "res/lobby/GameIcons/AreaGameTitle/429006.png"
    }

    export var AreaRadiosBg = { nomarl: 'mpCity.png', on: 'mpCityDeep1.png' }
    export var AreaRadiosText = {
        AnYang: { nomarl: 'AnYang.png', on: 'AnYang2.png' },
        ChuZhou: { nomarl: 'ChuZhou.png', on: 'ChuZhou2.png' },
        EnShi: { nomarl: 'EnShi.png', on: 'EnShi2.png' },
        EZhou: { nomarl: 'EZhou.png', on: 'EZhou2.png' },
        FuYang: { nomarl: 'FuYang.png', on: 'FuYang2.png' },
        HuangGang: { nomarl: 'HuangGang.png', on: 'HuangGang2.png' },
        HuangShi: { nomarl: 'HuangShi.png', on: 'HuangShi2.png' },
        InfoConfig: { nomarl: 'InfoConfig.xml', on: 'InfoConfig2.xml' },
        JiaoZuo: { nomarl: 'JiaoZuo.png', on: 'JiaoZuo2.png' },
        JingMen: { nomarl: 'JingMen.png', on: 'JingMen2.png' },
        JingZhou: { nomarl: 'JingZhou.png', on: 'JingZhou2.png' },
        KaiFeng: { nomarl: 'KaiFeng.png', on: 'KaiFeng2.png' },
        LuoHe: { nomarl: 'LuoHe.png', on: 'LuoHe2.png' },
        LuoYang: { nomarl: 'LuoYang.png', on: 'LuoYang2.png' },
        NanYang: { nomarl: 'NanYang.png', on: 'NanYang2.png' },
        PingDingShan: { nomarl: 'PingDingShan.png', on: 'PingDingShan2.png' },
        PuYang: { nomarl: 'PuYang.png', on: 'PuYang2.png' },
        QianJiang: { nomarl: 'QianJiang.png', on: 'QianJiang2.png' },
        SanMenXia: { nomarl: 'SanMenXia.png', on: 'SanMenXia2.png' },
        ShangQiu: { nomarl: 'ShangQiu.png', on: 'ShangQiu2.png' },
        ShiYan: { nomarl: 'ShiYan.png', on: 'ShiYan2.png' },
        SuiZhou: { nomarl: 'SuiZhou.png', on: 'SuiZhou2.png' },
        TianMen: { nomarl: 'TianMen.png', on: 'TianMen2.png' },
        WuHan: { nomarl: 'WuHan.png', on: 'WuHan2.png' },
        XiangYang: { nomarl: 'XiangYang.png', on: 'XiangYang2.png' },
        XianNing: { nomarl: 'XianNing.png', on: 'XianNing2.png' },
        XianTao: { nomarl: 'XianTao.png', on: 'XianTao2.png' },
        XiaoGan: { nomarl: 'XiaoGan.png', on: 'XiaoGan2.png' },
        XinXiang: { nomarl: 'XinXiang.png', on: 'XinXiang2.png' },
        XinYang: { nomarl: 'XinYang.png', on: 'XinYang2.png' },
        XuChang: { nomarl: 'XuChang.png', on: 'XuChang2.png' },
        YiChang: { nomarl: 'YiChang.png', on: 'YiChang2.png' },
        ZhangJiaKou: { nomarl: 'ZhangJiaKou.png', on: 'ZhangJiaKou2.png' },
        ZhengZhou: { nomarl: 'ZhengZhou.png', on: 'ZhengZhou2.png' },
        ZhouKou: { nomarl: 'ZhouKou.png', on: 'ZhouKou2.png' },
        ZhuMaDian: { nomarl: 'ZhuMaDian.png', on: 'ZhuMaDian2.png' }
    }


    for (var x in GameIcons) {
        res['GameIcons_' + x] = GameIcons[x];
    }

    for (var x in res) {
        kaayou.ResManager.getInstance().pushRes(res[x]);
    }


    export function uninstall() {
        kaayou.NetManager.getInstance().deleteSocket('lobby');
        kaayou.UIManager.getInstance().uninstallScene('lobby');
        kaayou.ControllerManager.getInstance().uninstall('lobby');
    }
}