namespace tea {
    export var res = {
        AddTable_json: "res/lobby/TeaHouse/TH_MixFloor/TH_AddTable.json",
        AntiIndulgencePanel_json: "res/lobby/TeaHouse/TH_AntiIndulgence/TH_AntiIndulgencePanel.json",
        AntiIndulgencePanelControlDialog_json: "res/lobby/TeaHouse/TH_AntiIndulgence/TH_AntiIndulgence_Config_Panel.json",
        AuthPanel_json: "res/lobby/TeaHouse/TH_AuthPanel/TH_AuthPanel.json",
        CreateActivity_Json: "res/lobby/TeaHouse/TH_TeaHouseActivity/TH_CreateActivityPanel.json",
        DescriptionPanel_Json: "res/lobby/TeaHouse/TH_ViewPanel/TH_Description.json",
        DistancePanel_Json: "res/lobby/TeaHouse/TH_DistancePanel/TH_DistancePanel.json",
        FcmBatch_json: "res/lobby/TeaHouse/TH_AntiIndulgence/PopupPanel/TH_FcmBatch.json",
        ForbidCaptain_json: "res/lobby/TeaHouse/TH_MemberPanel/TH_ForbidCaptain.json",
        InvitePanel_Json: "res/lobby/TeaHouse/TH_InvitePanel/TH_InvitePanel.json",
        MessageBox_json: "res/lobby/TeaHouse/TH_MessageBox/TH_MessageBox.json",
        MixFloor_json: "res/lobby/TeaHouse/TH_MenuBlocks/TH_MixFloorPanel.json",
        ReceiveInvitePanel_Json: "res/lobby/TeaHouse/TH_InvitePanel/TH_ReceiveInvitePanel.json",
        TH_AddMemberPanel_json: "res/lobby/TeaHouse/TH_MemberPanel/TH_AddMemberPanel.json",
        TH_AntiIndulgence_PointConfig_Panel_json: "res/lobby/TeaHouse/TH_AntiIndulgence/TH_AntiIndulgence_PointConfig_Panel.json",
        TH_MatchMenuPanel_json: "res/lobby/TeaHouse/TH_MatchPanel/TH_MatchMenuPanel.json",
        TH_MatchPanel_json: "res/lobby/TeaHouse/TH_MatchPanel/TH_MatchPanel.json",
        TH_TimeFliterPanel_json: "res/lobby/TeaHouse/TH_TimeFliterPanel/TH_TimeFliterPanel.json",
        TH_TimePanel_json: "res/lobby/TeaHouse/TH_TimePanel/TH_TimePanel.json",


        TH_WaitingMember_json: "res/lobby/TeaHouse/TH_MixFloor/TH_WaitingMember.json",
        NoDeskmate_json: "res/lobby/TeaHouse/TH_NoDeskmate/TH_NoDeskmate.json",
        ParterMemberPanel_json: "res/lobby/TeaHouse/TH_PartnerMemberPanel/TH_PartnerMemberPanel.json",
        ParterMemberRecordPanel_json: "res/lobby/TeaHouse/TH_MemberPanel/TH_PartnerMemberRecordPanel.json",
        SendInvitePanel_Json: "res/lobby/TeaHouse/TH_InvitePanel/TH_SendInvitePanel.json",
        TeaHouse_json: "res/lobby/TeaHouse/TeaHouseScene.json",
        TiredEditPanel_json: "res/lobby/TeaHouse/TH_AntiIndulgence/PopupPanel/TH_TiredEditPanel.json",
        TiredGiveConfirmPanel_json: "res/lobby/TeaHouse/TH_AntiIndulgence/PopupPanel/TH_TiredGiveConfirmPanel.json",
        TiredGivePanel_json: "res/lobby/TeaHouse/TH_AntiIndulgence/PopupPanel/TH_TiredGivePanel.json",
        TopMenuBlock_json: "res/lobby/TeaHouse/TH_MenuBlocks/TH_TopMenuBlock.json",
        SettingMenuPanel_json: "res/lobby/TeaHouse/TH_MenuBlocks/TH_SettingMenuPanel.json",
        BottonMenuBlock_json: "res/lobby/TeaHouse/TH_MenuBlocks/TH_BottomMenuBlock.json",
        ChangeFloorBlock_json: "res/lobby/TeaHouse/TH_ChangeFloorPanel/TH_ChangeFloorBlock.json",
        ChangeFloorPanel_json: "res/lobby/TeaHouse/TH_ChangeFloorPanel/TH_ChangeFloorPanel.json",
        ManagerPanel_json: "res/lobby/TeaHouse/TH_ManagerPanel/TH_ManagerPanel.json",
        MemberPanel_json: "res/lobby/TeaHouse/TH_MemberPanel/TH_MemberPanel.json",
        ViewPanel_json: "res/lobby/TeaHouse/TH_ViewPanel/TH_ViewPanel.json",
        PartnerTip_Json: "res/lobby/TeaHouse/TH_ViewPanel/TH_Partner.json",
        CreatePanel_json: "res/lobby/TeaHouse/TH_ViewPanel/TH_CreatePanel.json",
        JoinPanel_json: "res/lobby/TeaHouse/TH_ViewPanel/TH_JoinPanel.json",
        BlackListPanel_json: "res/lobby/TeaHouse/TH_BlackListPanel/TH_BlackListPanel.json",
        PrivacyPanel_json: "res/lobby/TeaHouse/TH_PrivacyPanel/TH_PrivacyPanel.json",
        FrozePanel_json: "res/lobby/TeaHouse/TH_FrozePanel/TH_FrozePanel.json",
        TableDetailPanel_json: "res/lobby/TeaHouse/TH_Table/TH_TableDetailPanel.json",
        Table_Block_json: "res/lobby/TeaHouse/TH_Table/TH_Table_Block.json",
        Table_Cell1_json: "res/lobby/TeaHouse/TH_Table/TH_Table_Cell1.json",
        RecordPanel_json: "res/lobby/TeaHouse/TH_RecordPanel/TH_RecordPanel.json",
        RecordDetailDialog_json: "res/lobby/TeaHouse/TH_RecordPanel/TH_RecordDetailDialog.json",
        RecordDetail_Json: "res/lobby/TeaHouse/TH_RecordPanel/TH_RecordDetail.json",
        SharePanel_json: "res/lobby/TeaHouse/TH_SharePanel/TH_SharePanel.json",
        MemberRemove_Json: "res/lobby/TeaHouse/TH_MemberPanel/TH_RemoveMember.json",
        MemberUserInfo_Json: "res/lobby/TeaHouse/TH_MemberPanel/TH_MemberUserPanel.json",
        PmdPanel_Json: "res/lobby/TeaHouse/TH_PmdPanel/TH_PmdPanel.json",
        ActivityPanel_Json: "res/lobby/TeaHouse/TH_TeaHouseActivity/TH_TeaHouseActivity.json",
        tableStylePlist: "res/lobby/TeaHouse/TH_Table/Th_tableStyle.plist",
        TH_FcmPlayerDeatail_json: "res/lobby/TeaHouse/TH_AntiIndulgence/PopupPanel/TH_FcmPlayerDeatail.json",
        TH_FcmWareHousePop_Json: "res/lobby/TeaHouse/TH_AntiIndulgence/PopupPanel/TH_WareHouseOpPanel.json",
        TH_FcmDesPanel_Json: "res/lobby/TeaHouse/TH_AntiIndulgence/PopupPanel/TH_FcmDesPanel.json",
        // Th_DelaPanel: "res/lobby/TeaHouse/TH_DelaminationSetting/TH_delaPanel.json",
        TH_PartnerMemberPopPanel: "res/lobby/TeaHouse/TH_AntiIndulgence/PopupPanel/TH_FcmMemberCountPopPanel.json",
        TH_ChooseFastGamePanel: "res/lobby/TeaHouse/TH_MenuBlocks/TH_ChooseFastGame.json",
        TH_JoinTableSetPanel: "res/lobby/TeaHouse/TH_MenuBlocks/TH_JoinTableSetPanel.json",
        TH_SetAuthPowerPanel: "res/lobby/TeaHouse/TH_MenuBlocks/TH_AuthPowerPanel.json",
        TH_MergeUserPanel_json: "res/lobby/TeaHouse/TH_MergeUserPanel/TH_MergeUserPanel.json",
        TH_MergeUserDialog_All_json: "res/lobby/TeaHouse/TH_MergeUserPanel/TH_MergeUserDialog_All.json",
        TH_MergeUserCheckDialog_json: "res/lobby/TeaHouse/TH_MergeUserPanel/TH_MergeUserCheckDialog.json",
        TH_MergeUser_plist: "res/lobby/TeaHouse/TH_MergeUserPanel/TH_MergeUser.plist",
        TH_PropotionPanel_json: "res/lobby/TeaHouse/TH_PropotionPanel/TH_PropotionPanel.json",
        TH_PropotionConfigChangeDialog_json: "res/lobby/TeaHouse/TH_PropotionPanel/TH_PropotionConfigChangeDialog.json",
        TH_ProportionInfoDialog_json: "res/lobby/TeaHouse/TH_PropotionPanel/TH_ProportionInfoDialog.json",
        TH_ProportionNoAllianceInfoDialog_json: "res/lobby/TeaHouse/TH_PropotionPanel/TH_ProportionNoAllianceInfoDialog.json",
        TH_RecordNoAllianceInfoDialog_json: "res/lobby/TeaHouse/TH_RecordPanel/TH_RecordNoAllianceInfoDialog.json",
        TH_RecordMemberDetail_json: "res/lobby/TeaHouse/TH_RecordPanel/MemberDetail/TH_RecordMemberDetail.json",
        TH_PropotionConfigDialog_json: "res/lobby/TeaHouse/TH_PropotionPanel/TH_PropotionConfigDialog.json",
        TH_ProportionBindDialog_json: "res/lobby/TeaHouse/TH_PropotionPanel/TH_ProportionBindDialog.json",
        TH_ShowTableCountPanel: "res/lobby/TeaHouse/TH_MenuBlocks/TH_ShowtablePanel.json",
        TH_ProportionDeletedFloorPopDetail_json: "res/lobby/TeaHouse/TH_PropotionPanel/TH_ProportionDeletedFloorCountDetail.json",
        TH_ProportionSetGroup_json: "res/lobby/TeaHouse/TH_PropotionPanel/TH_ProportionSetGroup.json",
        TH_Propotion_FloorConfig_Dialog_json: "res/lobby/TeaHouse/TH_PropotionPanel/TH_Propotion_FloorConfig_Dialog.json",
        TH_MatchRewardConfigDialog_json: "res/lobby/TeaHouse/TH_AntiIndulgence/TH_MatchRewardConfigDialog.json",
        TH_TimeMatchPmPanel: "res/lobby/TeaHouse/TH_MenuBlocks/TH_TimeMatchPanel.json",
        TH_SearchTablePanelJson: "res/lobby/TeaHouse/TH_MenuBlocks/Bottom/TH_SearchMemTablePanel.json",
        TH_setbg_Json: "res/lobby/TeaHouse/TH_MenuBlocks/TH_BgSetPanel.json",
        TH_FortuneWheel: "res/lobby/TeaHouse/TH_FortuneWheel/TH_FortuneWheel.json",
        TH_FortuneWheel_Animate_atlas: "res/lobby/TeaHouse/TH_FortuneWheel/animate/xiaodeng.atlas",
        TH_FortuneWheel_Animate_png: "res/lobby/TeaHouse/TH_FortuneWheel/animate/xiaodeng.png",
        TH_FortuneWheel_Animate_json: "res/lobby/TeaHouse/TH_FortuneWheel/animate/xiaodeng.json",
        TH_FortuneWheel_playsound_mp3: "res/lobby/TeaHouse/TH_FortuneWheel/playsound.mp3",
        TH_VIPFloorConfigDialog_json: "res/lobby/TeaHouse/TH_VIPFloor/TH_VipFloorConfig.json",
        TH_priSetPanel_Json: "res/lobby/TeaHouse/TH_TeaHouseActivity/TH_AcPriSetPanel.json",
        TH_setTableBg_Json: "res/lobby/TeaHouse/TH_MenuBlocks/TH_TableBgSetPanel.json",
        TH_SetVipFloorMem_Json: "res/lobby/TeaHouse/TH_MenuBlocks/TH_SetVipMemberPanel.json",
        TH_RecordDialog: "res/lobby/TeaHouse/TH_RecordPanel/TH_RecordDialog.json",
        TH_SettingBlock_Json: "res/lobby/TeaHouse/TH_MenuBlocks/TH_SettingBlockPanel.json",
        TH_NoticePopSet_Json: "res/lobby/TeaHouse/TH_MenuBlocks/TH_NoticePopSet.json",
        TH_CardTips_Json: "res/lobby/TeaHouse/TH_MenuBlocks/TH_CardTipsPanel.json",

        RankListSetPanel_json: "res/lobby/TeaHouse/TH_MenuBlocks/TH_RankListSet.json",
        RankListPanel_json: "res/lobby/TeaHouse/TH_MenuBlocks/TH_RankListPanel.json",
    };
    for (var x in res) {
        kaayou.ResManager.getInstance().pushRes(res[x]);
    }
    export function uninstall() {
        kaayou.NetManager.getInstance().deleteSocket('tea');
        kaayou.UIManager.getInstance().uninstallScene('tea');
        kaayou.ControllerManager.getInstance().uninstall('tea');
    }

}

